name: Firebase PR Deploy
on: 
  pull_request:
    branches:
      - main
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Enable Corepack and Install Yarn v4
        run: |
          corepack enable
          corepack prepare yarn@stable --activate

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PULSECHECK_7CF2B }}
          projectId: pulsecheck-7cf2b
          
