name: Firebase Deploy
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

        # Enable Corepack and set up Yarn v4
      - name: Enable Corepack and Install Yarn v4
        run: |
          corepack enable
          corepack prepare yarn@stable --activate

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PULSECHECK_7CF2B }}
          channelId: live
          projectId: pulsecheck-7cf2b
