name: Run Vitest Tests

on:
    push:
        branches: [main, dev]
    pull_request:
        branches: [main, dev]

jobs:  
  test:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout Code  
        uses: actions/checkout@v4  

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
            node-version: 22
            cache: 'yarn'

      - name: Enable Corepack and Install Yarn v4
        run: |
            corepack enable
            corepack prepare yarn@stable --activate

      - name: Install Dependencies
        run: yarn install 

      - name: Run Vitest  
        run: yarn test  
